// Mock session data for the Session Viewer
// Sessions span multiple "desktops" (hosts) — running, idle, completed
// Each session has a thread of turns, plus optional branched evaluation thread

const SESSIONS = [
  {
    id: "S-104A",
    num: 104,
    host: "desk-01",
    title_en: "Migrate billing service to event-driven invoicing",
    title_kr: "빌링 서비스의 이벤트 기반 인보이싱 마이그레이션",
    model: "claude-haiku-4-5",
    provider: "anthropic",
    status: "live",
    started: "08:42",
    duration: "1h 47m",
    tokens: 28341,
    cached: 24902,
    turns: 24,
    cost: 0.142,
    hasBranch: true,
    summary_en: "Agent has reverse-engineered the existing Stripe webhook handler, identified 3 race conditions in the dual-write between Postgres and the message bus, and proposed an outbox pattern with idempotency keys derived from invoice_id+attempt. Currently drafting a migration plan that ships the outbox table first, then back-fills consumers in shadow mode for 48h before cutover.",
    summary_kr: "에이전트는 기존 Stripe 웹훅 핸들러를 리버스 엔지니어링하고, Postgres와 메시지 버스 간의 이중 쓰기에서 3개의 경쟁 조건을 식별하였으며, invoice_id+attempt에서 파생된 멱등성 키와 함께 아웃박스 패턴을 제안했습니다. 현재 아웃박스 테이블을 먼저 배포하고, 소비자를 48시간 동안 섀도우 모드로 백필한 후 컷오버하는 마이그레이션 계획을 작성 중입니다.",
    actions_en: [
      "Spec outbox table schema (invoice_id PK, payload JSONB, dispatched_at)",
      "Add idempotency middleware to webhook handler",
      "Roll back the optimistic-lock attempt in commit 8a2f1c3",
      "Schedule 48h shadow run, monitor diff against legacy emitter"
    ],
    actions_kr: [
      "아웃박스 테이블 스키마 명세 (invoice_id PK, payload JSONB, dispatched_at)",
      "웹훅 핸들러에 멱등성 미들웨어 추가",
      "커밋 8a2f1c3의 낙관적 잠금 시도 롤백",
      "48시간 섀도우 실행 예약, 레거시 이미터 대비 diff 모니터링"
    ],
  },
  {
    id: "S-103F",
    num: 103,
    host: "desk-01",
    title_en: "Triage flaky e2e suite on iOS 17 simulator",
    title_kr: "iOS 17 시뮬레이터의 불안정한 e2e 테스트 분류",
    model: "gpt-4o",
    provider: "openai",
    status: "idle",
    started: "07:15",
    duration: "2h 12m",
    tokens: 42118,
    cached: 39220,
    turns: 36,
    cost: 0.098,
    hasBranch: true,
    summary_en: "Agent isolated 11 flakes to a single timing assumption in the date-picker fixture (assumes ms-precision, simulator runs at 100ms tick). Patched 3 of them; 8 still need real-device verification. Waiting on user to confirm whether to bump tick rate or rewrite the fixture to be tick-agnostic.",
    summary_kr: "에이전트는 11개의 불안정한 테스트를 date-picker 픽스처의 단일 타이밍 가정(ms 정밀도 가정, 시뮬레이터는 100ms 틱으로 실행됨)으로 격리했습니다. 3개를 패치했고, 8개는 실제 디바이스 검증이 필요합니다. 틱 속도를 올릴지 또는 픽스처를 틱-불가지론적으로 다시 작성할지 사용자 확인을 대기 중입니다.",
    actions_en: [
      "Confirm decision: bump tick rate (cheap) vs rewrite fixture (correct)",
      "Run remaining 8 tests on physical iPhone 14",
      "Document the 100ms tick gotcha in CONTRIBUTING.md"
    ],
    actions_kr: [
      "결정 확인: 틱 속도 인상(저비용) vs 픽스처 재작성(정확)",
      "물리 iPhone 14에서 나머지 8개 테스트 실행",
      "CONTRIBUTING.md에 100ms 틱 함정 문서화"
    ],
  },
  {
    id: "S-102B",
    num: 102,
    host: "desk-02",
    title_en: "Draft RFC: cache-preserving sidecar evaluation",
    title_kr: "RFC 초안: 캐시 보존형 사이드카 평가",
    model: "claude-sonnet-4-5",
    provider: "anthropic",
    status: "live",
    started: "08:55",
    duration: "32m",
    tokens: 11204,
    cached: 9180,
    turns: 9,
    cost: 0.067,
    hasBranch: false,
    summary_en: "Agent has outlined the prefix-hash invariant, surveyed LangGraph thread forking, and is drafting a fan-out-without-fan-in pattern for the architecture section. Recommending append-only history + tool-based summary retrieval over inline context injection.",
    summary_kr: "에이전트는 접두사 해시 불변성을 개략화하고, LangGraph 스레드 분기를 조사했으며, 아키텍처 섹션을 위한 팬인 없는 팬아웃 패턴을 작성 중입니다. 인라인 컨텍스트 주입보다 추가 전용 기록과 도구 기반 요약 검색을 권장하고 있습니다.",
    actions_en: [
      "Finish §4 fan-out diagram",
      "Add Anthropic 20-block lookback caveat",
      "Cite Mem0 + LangSmith integration"
    ],
    actions_kr: [
      "§4 팬아웃 다이어그램 완성",
      "Anthropic 20-블록 룩백 주의사항 추가",
      "Mem0 + LangSmith 통합 인용"
    ],
  },
  {
    id: "S-101D",
    num: 101,
    host: "desk-02",
    title_en: "Refactor auth middleware to support tenant-scoped tokens",
    title_kr: "테넌트 범위 토큰을 지원하도록 인증 미들웨어 리팩터링",
    model: "gemini-2.5-pro",
    provider: "gemini",
    status: "live",
    started: "06:01",
    duration: "3h 04m",
    tokens: 61202,
    cached: 57340,
    turns: 47,
    cost: 0.183,
    hasBranch: true,
    summary_en: "Agent introduced a TenantContext that propagates through async_hooks, refactored 14 routes to read from it, and is now untangling a circular import between tenants/index.ts and middleware/auth.ts. Identified that the legacy session token must be re-issued on tenant switch — pending product confirmation.",
    summary_kr: "에이전트는 async_hooks를 통해 전파되는 TenantContext를 도입하고, 14개 경로를 이를 읽도록 리팩터링했으며, 현재 tenants/index.ts와 middleware/auth.ts 간의 순환 import를 해결 중입니다. 레거시 세션 토큰이 테넌트 전환 시 재발급되어야 함을 확인했으며, 제품 확인 대기 중입니다.",
    actions_en: [
      "Resolve circular import (extract TenantContext to shared/)",
      "Get product sign-off on token re-issue UX",
      "Add migration test covering cross-tenant session leak"
    ],
    actions_kr: [
      "순환 import 해결 (TenantContext를 shared/로 추출)",
      "토큰 재발급 UX에 대한 제품 승인 획득",
      "교차 테넌트 세션 누수를 다루는 마이그레이션 테스트 추가"
    ],
  },
  {
    id: "S-100E",
    num: 100,
    host: "desk-03",
    title_en: "Investigate latency spike in /search endpoint",
    title_kr: "/search 엔드포인트의 지연 시간 급증 조사",
    model: "claude-haiku-4-5",
    provider: "anthropic",
    status: "done",
    started: "yesterday",
    duration: "54m",
    tokens: 18402,
    cached: 16800,
    turns: 18,
    cost: 0.041,
    hasBranch: true,
    summary_en: "Agent traced the spike to a missing covering index on (org_id, created_at) added in a recent migration. Issued an online CREATE INDEX CONCURRENTLY, p95 dropped from 1240ms → 84ms within 6 minutes. Closed.",
    summary_kr: "에이전트는 최근 마이그레이션에 추가된 (org_id, created_at)에 누락된 커버링 인덱스로 급증을 추적했습니다. 온라인 CREATE INDEX CONCURRENTLY를 실행했고, p95가 6분 이내에 1240ms → 84ms로 감소했습니다. 종료됨.",
    actions_en: [
      "Resolved — index live on prod",
      "Add lint rule: created_at columns require index review"
    ],
    actions_kr: [
      "해결됨 — 인덱스가 프로덕션에 적용됨",
      "lint 규칙 추가: created_at 컬럼에는 인덱스 검토 필요"
    ],
  },
  {
    id: "S-099C",
    num: 99,
    host: "desk-03",
    title_en: "Onboard new design system tokens into Storybook",
    title_kr: "Storybook에 새 디자인 시스템 토큰 통합",
    model: "gpt-4o",
    provider: "openai",
    status: "done",
    started: "yesterday",
    duration: "1h 19m",
    tokens: 22910,
    cached: 19400,
    turns: 21,
    cost: 0.052,
    hasBranch: false,
    summary_en: "Synced 142 tokens from Figma to design-tokens/, regenerated TS types, and rewrote 6 Storybook addons that referenced legacy color names. All snapshot tests pass.",
    summary_kr: "Figma에서 design-tokens/로 142개 토큰을 동기화하고, TS 타입을 재생성했으며, 레거시 색상 이름을 참조하는 6개의 Storybook 애드온을 다시 작성했습니다. 모든 스냅샷 테스트가 통과합니다.",
    actions_en: ["Closed — merged to main"],
    actions_kr: ["종료됨 — main에 병합됨"],
  },
  {
    id: "S-098H",
    num: 98,
    host: "desk-04",
    title_en: "Reproduce intermittent 502 from edge gateway",
    title_kr: "엣지 게이트웨이의 간헐적 502 재현",
    model: "claude-sonnet-4-5",
    provider: "anthropic",
    status: "live",
    started: "08:11",
    duration: "55m",
    tokens: 33105,
    cached: 30210,
    turns: 19,
    cost: 0.121,
    hasBranch: false,
    summary_en: "Agent reproduced under sustained 800rps with TLS handshake delays. Suspecting a connection pool starvation in the upstream service mesh. Currently building a minimal repro with toxiproxy.",
    summary_kr: "에이전트는 지속적인 800rps와 TLS 핸드셰이크 지연 하에서 재현했습니다. 업스트림 서비스 메시의 연결 풀 고갈을 의심하고 있습니다. 현재 toxiproxy로 최소 재현을 구축 중입니다.",
    actions_en: [
      "Capture toxiproxy repro and attach pcap",
      "Check linkerd connection pool config",
      "Bisect across last 7d of mesh deploys"
    ],
    actions_kr: [
      "toxiproxy 재현 캡처 및 pcap 첨부",
      "linkerd 연결 풀 구성 확인",
      "지난 7일간의 메시 배포 이분 검색"
    ],
  },
  {
    id: "S-097K",
    num: 97,
    host: "desk-04",
    title_en: "Generate Q3 OKR retrospective from session telemetry",
    title_kr: "세션 텔레메트리에서 Q3 OKR 회고 생성",
    model: "gemini-2.5-flash",
    provider: "gemini",
    status: "idle",
    started: "yesterday",
    duration: "12m",
    tokens: 8204,
    cached: 6100,
    turns: 6,
    cost: 0.014,
    hasBranch: false,
    summary_en: "Pulled metrics for Q3, drafted 3 sections. Awaiting approval on tone before finishing the leadership-facing TL;DR.",
    summary_kr: "Q3 메트릭을 가져와 3개 섹션 초안을 작성했습니다. 리더십 대상 TL;DR을 마무리하기 전에 톤에 대한 승인을 대기 중입니다.",
    actions_en: ["Confirm tone (formal vs conversational)", "Finish leadership TL;DR"],
    actions_kr: ["톤 확인 (격식 vs 대화형)", "리더십 TL;DR 마무리"],
  },
];

// Sample turn data per session — only fully expanded for the first selected
const TURNS_DEFAULT = [
  { role: "system", body_en: "You are a senior engineer assisting on production migrations. Use tools sparingly and explain trade-offs.", body_kr: "당신은 프로덕션 마이그레이션을 지원하는 시니어 엔지니어입니다. 도구를 신중하게 사용하고 트레이드오프를 설명하세요.", cached: true, tokens: 142 },
  { role: "user",   body_en: "Walk through the current Stripe webhook flow and tell me what could double-fire on retry.", body_kr: "현재 Stripe 웹훅 흐름을 살펴보고 재시도 시 이중 발생할 수 있는 것을 알려주세요.", cached: true, tokens: 38 },
  { role: "tool",   call: "read_file", args: "billing/webhook.ts", body_en: "Returned 412 lines.", body_kr: "412줄 반환됨.", cached: true, tokens: 4108 },
  { role: "asst",   body_en: "There are three places dual-writes can fire twice on retry: (1) the upsert into invoices then a publish into the bus is non-atomic, (2) the retry header is read after the row write commits, and (3) idempotency_key is derived from a timestamp that drifts on replay.", body_kr: "재시도 시 이중 쓰기가 두 번 발생할 수 있는 세 곳: (1) invoices에 대한 upsert와 bus로의 publish가 원자적이지 않음, (2) 재시도 헤더가 행 쓰기 커밋 후 읽힘, (3) idempotency_key가 재생 시 드리프트되는 타임스탬프에서 파생됨.", cached: true, tokens: 268 },
  { role: "user",   body_en: "Propose an outbox + idempotency key strategy.", body_kr: "아웃박스 + 멱등성 키 전략을 제안해 주세요.", cached: true, tokens: 14 },
  { role: "asst",   body_en: "Outbox table sits next to invoices in the same transaction. A lightweight relay reads ordered rows and emits to the bus with at-least-once semantics. Idempotency key = sha256(invoice_id + attempt + tenant_id).", body_kr: "아웃박스 테이블은 동일한 트랜잭션 내에서 invoices 옆에 위치합니다. 경량 릴레이가 정렬된 행을 읽고 at-least-once 시맨틱으로 버스에 전송합니다. 멱등성 키 = sha256(invoice_id + attempt + tenant_id).", cached: true, tokens: 312 },
  { role: "tool",   call: "edit_file", args: "billing/outbox.sql", body_en: "Created outbox table + index. 38 LOC.", body_kr: "아웃박스 테이블 + 인덱스 생성. 38 LOC.", cached: true, tokens: 410 },
  { role: "user",   body_en: "What's the rollback story if the relay falls behind?", body_kr: "릴레이가 뒤처질 경우의 롤백 시나리오는 무엇인가요?", cached: false, tokens: 16, live: true },
];

window.SESSIONS = SESSIONS;
window.TURNS_DEFAULT = TURNS_DEFAULT;
